import { Button } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image';
import About from '../components/home/about';
import Banner from '../components/home/banner';
import Layout from '../components/layout';
import bgImage from '../public/images/portflio-bg.jpg'


export default function Home() {

  return (
    <>
      <Layout home>
        <Head>
          <title>My Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Banner/>
        <div style={{ backgroundImage: `url(${bgImage.src})`, backgroundPosition: 'fixed', backgroundSize: 'cover', backgroundRepeat: 'no-repeat',  }}>
          <About/>
        </div>
      </Layout>
    </>
  )
}



